#pragma once

#include "RE/Skyrim.h"
#include "SKSE/SKSE.h"

#include <algorithm>
#include <array>
#include <cstdint>
#include <filesystem>
#include <memory>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace logger = SKSE::log;

// Required: the plugin declaration generated by add_commonlibsse_plugin uses
// "..."sv literals and gets this header force-included. Removing this line
// breaks the build with C3688.
using namespace std::literals;